@startuml

interface MetricEventHub {
  + subscribeToMetrics(handler: (Metric) => void): void
  + publishMetric(metric: Metric): void
}
note right of MetricEventHub: Event Hub

class MetricEventHubGossip {
  + subscribeToMetrics(handler: (Metric) => void): void
  + publishMetric(metric: Metric): void
}

MetricEventHubGossip --|> MetricEventHub
note right of MetricEventHubGossip: Gossip-based\nEvent Hub, implementation


@enduml
