version: "3.8"

services:
  tor1:
    build:
      context: ./tor
      dockerfile: Dockerfile
    volumes:
      - tor1-data:/var/lib/tor/hidden_service
    networks:
      - test-network

  node1:
    build:
      context: ./libp2p
      dockerfile: Dockerfile
    environment:
      - TOR_PROXY=socks5h://tor1:9050
      - ONION_ADDRESS=i72bhp2qv7ibm5pce3kywxpody3bwjacbzn3w2ggmzckzmptc5rkogid.onion
    networks:
      - test-network
    depends_on:
      - tor1

  tor2:
    build:
      context: ./tor
      dockerfile: Dockerfile
    volumes:
      - tor2-data:/var/lib/tor/hidden_service
    networks:
      - test-network

  node2:
    build:
      context: ./libp2p
      dockerfile: Dockerfile
    environment:
      - TOR_PROXY=socks5h://tor2:9050
      - ONION_ADDRESS=4pfz6moqvxj5ggvisjhv7ripfjldck5vyntzbrygpuekaog4wpyxypad.onion
    networks:
      - test-network
    depends_on:
      - tor2

volumes:
  tor1-data:
  tor2-data:

networks:
  test-network:
