services:
  provider-1:
    #image: pagahubbing/anonymous-shard-provider-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      - HOST=cuffhcxwm63td4e2n67o3bq7j5qc2ipuegtsuo7cwi3i2j3oxns47kid
      - PORT=3000
      - BOOTSTRAP_NODE_ADDRESS_1=cuffhcxwm63td4e2n67o3bq7j5qc2ipuegtsuo7cwi3i2j3oxns47kid
      - BOOTSTRAP_NODE_PORT_1=3000
      # - LOCAL_BOOTSTRAP_NODE_ADDRESS_1=127.0.0.1
      # - LOCAL_BOOTSTRAP_NODE_PORT_1=3000
      - BOOTSTRAP_NODE_ADDRESS_2=rlnox5ie2e6crrdajtohhwtqp5oz3nt3qewr24egczwftixh2jbgv4yd
      - BOOTSTRAP_NODE_PORT_2=3000
      # - LOCAL_BOOTSTRAP_NODE_ADDRESS_2=127.0.0.1
      # - LOCAL_BOOTSTRAP_NODE_PORT_2=3001
      # and so on and so forth for multiple bootstrap nodes
    volumes:
      - tor1-data:/var/lib/tor/hidden_service
    networks:
      - test-network

  provider-2:
    #image: pagahubbing/anonymous-shard-provider-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      - HOST=rlnox5ie2e6crrdajtohhwtqp5oz3nt3qewr24egczwftixh2jbgv4yd
      - PORT=3000
      - BOOTSTRAP_NODE_ADDRESS_1=cuffhcxwm63td4e2n67o3bq7j5qc2ipuegtsuo7cwi3i2j3oxns47kid
      - BOOTSTRAP_NODE_PORT_1=3000
      # - LOCAL_BOOTSTRAP_NODE_ADDRESS_1=127.0.0.1
      # - LOCAL_BOOTSTRAP_NODE_PORT_1=3000
      - BOOTSTRAP_NODE_ADDRESS_2=rlnox5ie2e6crrdajtohhwtqp5oz3nt3qewr24egczwftixh2jbgv4yd
      - BOOTSTRAP_NODE_PORT_2=3000
      # - LOCAL_BOOTSTRAP_NODE_ADDRESS_2=127.0.0.1
      # - LOCAL_BOOTSTRAP_NODE_PORT_2=3001
    volumes:
      - tor2-data:/var/lib/tor/hidden_service
    networks:
      - test-network

volumes:
  tor1-data:
    name: tor1-data # Persistent volume for node1, so that in case of tor the onion address remains the same
  tor2-data:
    name: tor2-data # Persistent volume for node2, so that in case of tor the onion address remains the same

networks:
  test-network:
    driver: bridge
