services:
  node-1:
    #image: pagahubbing/anonymous-shard-provider-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=a7oxxul76cei44utvngfg2tnhqmedkjlwiiudbaqzer5z5w75gpgyeqd
      - PORT=3000
      - BOOTSTRAP_NODE_ADDRESS_1=a7oxxul76cei44utvngfg2tnhqmedkjlwiiudbaqzer5z5w75gpgyeqd
      - BOOTSTRAP_NODE_PORT_1=3000
      - BOOTSTRAP_NODE_ADDRESS_2=eww4sjfxwj6vgucebupol2nk7yhbvhjzxo2v4t46f42gukn3btknzvid
      - BOOTSTRAP_NODE_PORT_2=3000
      # and so on and so forth for multiple bootstrap nodes
    ports:
      - "3000:3000"
      - "9050:9050"
    volumes:
      - tor1-data:/var/lib/tor/hidden_service
    networks:
      - test-network

  node-2:
    #image: pagahubbing/anonymous-shard-provider-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=eww4sjfxwj6vgucebupol2nk7yhbvhjzxo2v4t46f42gukn3btknzvid
      - PORT=3000
      - BOOTSTRAP_NODE_ADDRESS_1=a7oxxul76cei44utvngfg2tnhqmedkjlwiiudbaqzer5z5w75gpgyeqd
      - BOOTSTRAP_NODE_PORT_1=3000
      - BOOTSTRAP_NODE_ADDRESS_2=eww4sjfxwj6vgucebupol2nk7yhbvhjzxo2v4t46f42gukn3btknzvid
      - BOOTSTRAP_NODE_PORT_2=3000
      # and so on and so forth for multiple bootstrap nodes
    ports:
      - "3001:3000"
      - "9051:9050"
    volumes:
      - tor2-data:/var/lib/tor/hidden_service
    networks:
      - test-network

volumes:
  tor1-data:
    name: tor1-data # Persistent volume for node1, so that in case of tor the onion address remains the same
  tor2-data:
    name: tor2-data # Persistent volume for node2, so that in case of tor the onion address remains the same

networks:
  test-network:
    driver: bridge
