services:
  consumer:
    build:
      context: ..
      dockerfile: consumer-node/Dockerfile
      args:
        - DEV_API_KEY=apikey-dev
        - API_PORT=4900
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      #- HOST=h3se2r3j7t7txezijeaffx45pjbtd32y452zdjkjexzcs7q767vqx5ad
      - HOST=consumer
      - PORT=3000
      - BOOTSTRAP_NODE_ADDRESS_1=cuffhcxwm63td4e2n67o3bq7j5qc2ipuegtsuo7cwi3i2j3oxns47kid
      - BOOTSTRAP_NODE_PORT_1=3000
      - LOCAL_BOOTSTRAP_NODE_ADDRESS_1=provider-1
      - LOCAL_BOOTSTRAP_NODE_PORT_1=3000
      - BOOTSTRAP_NODE_ADDRESS_2=rlnox5ie2e6crrdajtohhwtqp5oz3nt3qewr24egczwftixh2jbgv4yd
      - BOOTSTRAP_NODE_PORT_2=3000
      - LOCAL_BOOTSTRAP_NODE_ADDRESS_2=provider-2
      - LOCAL_BOOTSTRAP_NODE_PORT_2=3001
    ports:
      - "4900:4000"
      - "8085:8080"
    volumes:
      - tor1-data-consumer:/var/lib/tor/hidden_service
    networks:
      - test-network

volumes:
  tor1-data-consumer:
    name: tor1-data-consumer # Persistent to keep the same onion address

networks:
  test-network:
    driver: bridge

