services:

  provider-node-frontend:
    image: pagahubbing/provider-node-frontend
    container_name: provider-node-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ANONYMOUS_MODE: false
        PROVIDER_HOST: 127.0.0.1
        PROVIDER_PORT: 3002
        DEV_API_KEY: apikey-dev
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
