services:

  provider-node-frontend:
    image: pagahubbing/provider-node-frontend
    container_name: provider-node-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ANONYMOUS_MODE: true
        PROVIDER_HOST: cuffhcxwm63td4e2n67o3bq7j5qc2ipuegtsuo7cwi3i2j3oxns47kid.onion
        PROVIDER_PORT: 3000
        DEV_API_KEY: apikey-dev
        SOCKS5_HOST: 127.0.0.1
        SOCKS5_PORT: 9050
    environment:
      ANONYMOUS_MODE: true
    restart: on-failure
    ports:
      # - 8080:8080
      - 9050:9050
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
