@startuml
actor Consumer
participant Peer1
participant Peer2
participant IPFS

Consumer -> Consumer: Generate key pair (public/private)
Consumer -> Peer1: Submit task + public key
Peer1 -> Peer1: Evaluate ability to execute the task
alt Can execute the task
    Peer1 -> IPFS: Save result encrypted with public key
    IPFS -> Peer1: Return content identifier
    Peer1 -> Consumer: Return information to retrieve the result
else Cannot execute the task
    Peer1 -> Peer2: Force forward task to the best peer
    Peer2 -> Peer2: Evaluate ability to execute the task
    Peer2 -> IPFS: Save result encrypted with public key
    IPFS -> Peer2: Return content identifier
    Peer2 -> Consumer: Return information to retrieve the result
end
Consumer -> IPFS: Retrieve encrypted result
Consumer -> Consumer: Decrypt result with private key
Consumer -> Consumer: Save result locally
@enduml
