services:
  provider-1:
    #image: pagahubbing/anonymous-shard-provider-node:latest
    container_name: local-provider-1
    build:
      context: ..
      dockerfile: provider-node/Dockerfile
      args:
        - DEV_API_KEY=apikey-dev
        - API_PORT=4000
    environment:
      - ANONYMOUS_MODE=false
      - DEV_API_KEY=apikey-dev
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      - HOST=local-provider-1
      - PORT=3000
      - LOCAL_BOOTSTRAP_NODE_ADDRESS_1=local-provider-1
      - LOCAL_BOOTSTRAP_NODE_PORT_1=3000
      - LOCAL_BOOTSTRAP_NODE_ADDRESS_2=local-provider-2
      - LOCAL_BOOTSTRAP_NODE_PORT_2=3001
    ports:
      - "4000:4000"
      - "8080:8080"
    volumes:
      - tor1-data:/var/lib/tor/hidden_service
    networks:
      - test-network

  provider-2:
    #image: pagahubbing/anonymous-shard-provider-node:latest
    container_name: local-provider-2
    build:
      context: ..
      dockerfile: provider-node/Dockerfile
      args:
        - DEV_API_KEY=apikey-dev
        - API_PORT=4001
    environment:
      - ANONYMOUS_MODE=false
      - DEV_API_KEY=apikey-dev
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      - HOST=local-provider-2
      - PORT=3001
      - LOCAL_BOOTSTRAP_NODE_ADDRESS_1=local-provider-1
      - LOCAL_BOOTSTRAP_NODE_PORT_1=3000
      - LOCAL_BOOTSTRAP_NODE_ADDRESS_2=local-provider-2
      - LOCAL_BOOTSTRAP_NODE_PORT_2=3001
    ports:
      - "4001:4001"
      - "8081:8080"
    volumes:
      - tor2-data:/var/lib/tor/hidden_service
    networks:
      - test-network

volumes:
  tor1-data:
    name: tor1-data # Persistent volume for node1, so that in case of tor the onion address remains the same
  tor2-data:
    name: tor2-data # Persistent volume for node2, so that in case of tor the onion address remains the same

networks:
  test-network:
    driver: bridge
