services:
  provider-1:
    image: pagahubbing/anonymous-shard-provider-node:latest
    container_name: tor-provider-1
    build:
      context: ..
      dockerfile: provider-node/Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      - PORT=3000
      - API_PORT=4000
      - BOOTSTRAP_NODE_ADDRESS_1=cuffhcxwm63td4e2n67o3bq7j5qc2ipuegtsuo7cwi3i2j3oxns47kid
      - BOOTSTRAP_NODE_PORT_1=3000
      - BOOTSTRAP_NODE_ADDRESS_2=rlnox5ie2e6crrdajtohhwtqp5oz3nt3qewr24egczwftixh2jbgv4yd
      - BOOTSTRAP_NODE_PORT_2=3000
    ports:
      - "4000:4000"
      - "8080:8080"
    volumes:
      - tor1-data:/var/lib/tor/hidden_service
    networks:
      - anonymous-shard-network

  provider-2:
    image: pagahubbing/anonymous-shard-provider-node:latest
    container_name: tor-provider-2
    build:
      context: ..
      dockerfile: provider-node/Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      # - HOST=rlnox5ie2e6crrdajtohhwtqp5oz3nt3qewr24egczwftixh2jbgv4yd
      - PORT=3000
      - API_PORT=4001
      - BOOTSTRAP_NODE_ADDRESS_1=cuffhcxwm63td4e2n67o3bq7j5qc2ipuegtsuo7cwi3i2j3oxns47kid
      - BOOTSTRAP_NODE_PORT_1=3000
      - BOOTSTRAP_NODE_ADDRESS_2=rlnox5ie2e6crrdajtohhwtqp5oz3nt3qewr24egczwftixh2jbgv4yd
      - BOOTSTRAP_NODE_PORT_2=3000
    ports:
      - "4001:4000"
      - "8081:8080"
    volumes:
      - tor2-data:/var/lib/tor/hidden_service
    networks:
      - anonymous-shard-network

  provider-3:
    image: pagahubbing/anonymous-shard-provider-node:latest
    container_name: tor-provider-3
    build:
      context: ..
      dockerfile: provider-node/Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      # - HOST=dtnx2clailpt3xt3bib4ti247s7n4mj4v55d35fyowop4aw6buzl3zad
      - PORT=3000
      - API_PORT=4002
      - BOOTSTRAP_NODE_ADDRESS_1=cuffhcxwm63td4e2n67o3bq7j5qc2ipuegtsuo7cwi3i2j3oxns47kid
      - BOOTSTRAP_NODE_PORT_1=3000
      - BOOTSTRAP_NODE_ADDRESS_2=rlnox5ie2e6crrdajtohhwtqp5oz3nt3qewr24egczwftixh2jbgv4yd
      - BOOTSTRAP_NODE_PORT_2=3000
    ports:
      - "4002:4000"
      - "8082:8080"
    volumes:
      - tor3-data:/var/lib/tor/hidden_service
    networks:
      - anonymous-shard-network

  consumer-1:
    image: pagahubbing/anonymous-shard-consumer-node:latest
    container_name: tor-consumer-1
    build:
      context: ..
      dockerfile: consumer-node/Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      #- HOST=h3se2r3j7t7txezijeaffx45pjbtd32y452zdjkjexzcs7q767vqx5ad
      - PORT=3000
      - API_PORT=4900
      - BOOTSTRAP_NODE_ADDRESS_1=cuffhcxwm63td4e2n67o3bq7j5qc2ipuegtsuo7cwi3i2j3oxns47kid
      - BOOTSTRAP_NODE_PORT_1=3000
      - BOOTSTRAP_NODE_ADDRESS_2=rlnox5ie2e6crrdajtohhwtqp5oz3nt3qewr24egczwftixh2jbgv4yd
      - BOOTSTRAP_NODE_PORT_2=3000
    ports:
      - "4900:4000"
      - "8085:8080"
    volumes:
      - tor1-data-consumer:/var/lib/tor/hidden_service
      - ./results:/app/consumer-node/results
    networks:
      - anonymous-shard-network

volumes:
  tor1-data:
    name: tor1-data # Persistent volume for nodes, so that in case of tor the onion address remains the same
  tor2-data:
    name: tor2-data
  tor3-data:
    name: tor3-data
  tor1-data-consumer:
    name: tor1-data-consumer

networks:
  anonymous-shard-network:
    name: anonymous-shard-network
    driver: bridge
    external: true
