services:
  provider-1:
    image: pagahubbing/anonymous-shard-provider-node:latest
    container_name: tor-provider-1
    build:
      context: ..
      dockerfile: provider-node/Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      - PORT=3000
      - API_PORT=4000
      - BOOTSTRAP_NODE=true
    ports:
      - "4000:4000"
      - "8080:8080"
    volumes:
      - tor1-data:/var/lib/tor/hidden_service
      - ./bootstrap:/app/bootstrap
    networks:
      - anonymous-shard-network

  provider-2:
    image: pagahubbing/anonymous-shard-provider-node:latest
    container_name: tor-provider-2
    build:
      context: ..
      dockerfile: provider-node/Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      - PORT=3000
      - API_PORT=4001
      - BOOTSTRAP_NODE=true
    ports:
      - "4001:4000"
      - "8081:8080"
    volumes:
      - tor2-data:/var/lib/tor/hidden_service
      - ./bootstrap:/app/bootstrap
    networks:
      - anonymous-shard-network

  provider-3:
    image: pagahubbing/anonymous-shard-provider-node:latest
    container_name: tor-provider-3
    build:
      context: ..
      dockerfile: provider-node/Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      - PORT=3000
      - API_PORT=4002
      - BOOTSTRAP_NODE=true
    ports:
      - "4002:4000"
      - "8082:8080"
    volumes:
      - tor3-data:/var/lib/tor/hidden_service
      - ./bootstrap:/app/bootstrap
    networks:
      - anonymous-shard-network

  provider-4:
    image: pagahubbing/anonymous-shard-provider-node:latest
    container_name: tor-provider-4
    build:
      context: ..
      dockerfile: provider-node/Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      - PORT=3000
      - API_PORT=4003
    ports:
      - "4003:4000"
      - "8083:8080"
    volumes:
      - tor4-data:/var/lib/tor/hidden_service
      - ./bootstrap:/app/bootstrap
    networks:
      - anonymous-shard-network

  provider-5:
    image: pagahubbing/anonymous-shard-provider-node:latest
    container_name: tor-provider-5
    build:
      context: ..
      dockerfile: provider-node/Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      - PINATA_API_KEY=1fd0fe489d865a398820
      - PINATA_API_SECRET=cac1872634ecbf108f0a00cdff9be7ecf04e0a2ad13a8211be5b80bb974e8974
      - PORT=3000
      - API_PORT=4004
    ports:
      - "4004:4000"
      - "8084:8080"
    volumes:
      - tor5-data:/var/lib/tor/hidden_service
      - ./bootstrap:/app/bootstrap
    networks:
      - anonymous-shard-network

  consumer-1:
    image: pagahubbing/anonymous-shard-consumer-node:latest
    container_name: tor-consumer-1
    build:
      context: ..
      dockerfile: consumer-node/Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      - PORT=3000
      - API_PORT=4900
    ports:
      - "4900:4000"
      - "8085:8080"
    volumes:
      - tor1-data-consumer:/var/lib/tor/hidden_service
      - ./results:/app/consumer-node/results
      - ./bootstrap:/app/bootstrap
    networks:
      - anonymous-shard-network

  consumer-2:
    image: pagahubbing/anonymous-shard-consumer-node:latest
    container_name: tor-consumer-2
    build:
      context: ..
      dockerfile: consumer-node/Dockerfile
    environment:
      - ANONYMOUS_MODE=true
      - DEV_API_KEY=apikey-dev
      - PORT=3000
      - API_PORT=4901
    ports:
      - "4901:4000"
      - "8086:8080"
    volumes:
      - tor2-data-consumer:/var/lib/tor/hidden_service
      - ./results:/app/consumer-node/results
      - ./bootstrap:/app/bootstrap
    networks:
      - anonymous-shard-network

volumes:
  tor1-data:
    name: tor1-data # Persistent volume for nodes, so that in case of tor the onion address remains the same
  tor2-data:
    name: tor2-data
  tor3-data:
    name: tor3-data
  tor4-data:
    name: tor4-data
  tor5-data:
    name: tor5-data
  tor1-data-consumer:
    name: tor1-data-consumer
  tor2-data-consumer:
    name: tor1-data-consumer

networks:
  anonymous-shard-network:
    name: anonymous-shard-network
    driver: bridge
    external: true
