openapi: 3.0.0
info:
    title: Provider monitoring Service API
    description: Provider nodes monitoring service API
    version: 1.0.0
tags:
    - name: Providers
      description: Operations related to providers
paths:
    /:
        get:
            responses:
                404:
                    description: Not found
